# -*- coding: utf-8 -*-
"""Money_Laundry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCdvqhKzNQUM0mI5lAmD3XdHJuwSl64V

<h1>AML Threshold Tuning with Python</h1>

Dataset : https://www.kaggle.com/datasets/anshankul/ibm-amlsim-example-dataset

<h2>Importing Libraries</h2>
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
pd.options.display.float_format = '{:,.4f}'.format

"""<h2>Unzip Dataset</h2>"""

## https://www.kaggle.com/datasets/anshankul/ibm-amlsim-example-dataset

# from zipfile import ZipFile
# with ZipFile('data.zip','r') as zip:
#     zip.extractall(path='data')

"""<h2>Reading account.csv and transactions.csv</h2>"""

acct_raw = pd.read_csv("accounts.csv", usecols=['ACCOUNT_ID','IS_FRAUD'])
acct_raw.rename(columns={'IS_FRAUD':'SUSPICIOUS'}, inplace=True)
acct_raw['SUSPICIOUS'] = acct_raw['SUSPICIOUS'].astype(int)
acct_raw

txn_raw = pd.read_csv("transactions.csv", usecols=['SENDER_ACCOUNT_ID','RECEIVER_ACCOUNT_ID','TX_AMOUNT'])
txn_raw

"""<h2>Create transaction summary for customers</h2>"""

credit_summary = txn_raw.groupby('RECEIVER_ACCOUNT_ID', as_index=False).agg({'TX_AMOUNT':['sum','count'], 'SENDER_ACCOUNT_ID':'nunique'})
credit_summary.columns=['ACCOUNT_ID','CREDIT_AMT','CREDIT_COUNT','CREDIT_CTPY']
credit_summary

debit_summary = txn_raw.groupby('SENDER_ACCOUNT_ID', as_index=False).agg({'TX_AMOUNT':['sum','count'], 'RECEIVER_ACCOUNT_ID':'nunique'})
debit_summary.columns=['ACCOUNT_ID','DEBIT_AMT','DEBIT_COUNT','DEBIT_CTPY']
debit_summary

acct = acct_raw.merge(credit_summary, on='ACCOUNT_ID', how='left').merge(debit_summary, on='ACCOUNT_ID', how='left').fillna(0).drop(columns=['ACCOUNT_ID'])
acct

"""<h2>Manual Threshold Simulation</h2>"""

for threshold in [100000, 500000, 1000000]:
    no_of_alert = (acct['CREDIT_AMT']>=threshold).sum()
    print(f'Threshold: {threshold} | No. of Alert: {no_of_alert}')

min_threshold = acct['CREDIT_AMT'].min()
max_threshold = acct['CREDIT_AMT'].max()

print(f'Minimum threshold = {min_threshold:,.0f}')
print(f'Maximum threshold = {max_threshold:,.0f}')

"""<h2>Train-Test Split</h2>"""

acct['SUSPICIOUS'].value_counts()

acct_train = pd.concat([
    acct[acct['SUSPICIOUS']==0].sample(frac=0.6, random_state=721),
    acct[acct['SUSPICIOUS']==1].sample(frac=0.6, random_state=721)]).sort_index()

acct_test = acct[~acct.index.isin(acct_train.index)]

print('Train Set\n', acct_train['SUSPICIOUS'].value_counts(), '\n')
print('Test Set\n', acct_test['SUSPICIOUS'].value_counts())

acct_train

acct_test

"""<h2>Statistical Distribution Analysis</h2>"""

acct_train.describe()

acct_train.hist(bins=50, figsize=(20,10), color='green', alpha=0.6)
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(2,3, figsize=(20,10))

for index, feature in enumerate(acct_train.columns[1:4]):

    data1 = acct_train[acct_train['SUSPICIOUS']==0][feature]
    data2 = acct_train[acct_train['SUSPICIOUS']==1][feature]

    ax[0][index].hist([data1, data2], bins=50, color=['blue','red'], alpha=0.6)
    ax[0][index].legend(labels=['NOT SUSPICIOUS','SUSPICIOUS'])
    ax[0][index].set_title(feature)
    ax[0][index].grid()

for index, feature in enumerate(acct_train.columns[4:]):

    data1 = acct_train[acct_train['SUSPICIOUS']==0][feature]
    data2 = acct_train[acct_train['SUSPICIOUS']==1][feature]

    ax[1][index].hist([data1, data2], bins=50, color=['blue','red'], alpha=0.6)
    ax[1][index].legend(labels=['NOT SUSPICIOUS','SUSPICIOUS'])
    ax[1][index].set_title(feature)
    ax[1][index].grid()

plt.tight_layout()
plt.show()

skewness = pd.concat([
    acct_train.skew(),
    acct_train[acct_train['SUSPICIOUS']==0].skew(),
    acct_train[acct_train['SUSPICIOUS']==1].skew()],axis=1)

skewness.columns=['ALL','NOT SUSPICIOUS','SUSPICIOUS']

skewness

"""<h2>Fallacy of Using the Mean+3SD as Threshold</h2>

Some may suggest using the mean + 3 standard deviations as the threshold. This practice is originated from empirical rule which suggests that the top 0.135% of customers will be captured at that threshold.

https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule

There are 2 fallacies here:
- Capturing top 0.135% of customers does not represent maximization of effectiveness.
- The feature distribution is not likely in normal distribution which you will get a different coverage with the threshold.
"""

# sample_size_df = pd.DataFrame()

# for feature in acct_train.columns[1:]:
#     mean = acct_train[feature].describe()['mean']
#     std = acct_train[feature].describe()['std']
#     sample_size = {}

#     for distance in range (0,6):
#         sample_size['feature'] = feature
#         sample_size[f'+{distance} std'] = len(acct_train[acct_train[feature]>=mean+distance*std]) / len(acct_train)


#     sample_size_df = sample_size_df.append(pd.DataFrame(sample_size, index=[0]), ignore_index=True)

sample_size_list = []

for feature in acct_train.columns[1:]:
    mean = acct_train[feature].mean()
    std = acct_train[feature].std()

    sample_size = {'feature': feature}
    for distance in range(0, 6):
        sample_size[f'+{distance} std'] = (
            (acct_train[feature] >= mean + distance * std).sum() / len(acct_train)
        )

    sample_size_list.append(sample_size)

sample_size_df = pd.DataFrame(sample_size_list)

sample_size_df

"""<h2>Threshold Simulation</h2>"""

min_threshold = acct_train['CREDIT_AMT'].min()
max_threshold = acct_train['CREDIT_AMT'].max()

print(f'Minimum threshold = {min_threshold:,.0f}')
print(f'Maximum threshold = {max_threshold:,.0f}')

"""<h3>Threshold Simulation at 75th Percentile</h3>"""

target_feature = 'CREDIT_AMT'
q = 0.75
threshold = acct_train[target_feature].quantile(q=q)

summary_train = {}
summary_train['feature'] = target_feature
summary_train['percentile'] = q
summary_train['threshold'] = threshold
summary_train['no_of_alerts'] = (acct_train[target_feature]>=threshold).sum()
summary_train['tp_count'] = ((acct_train[target_feature]>=threshold) & (acct_train['SUSPICIOUS']==1)).sum()
summary_train['fp_count'] = ((acct_train[target_feature]>=threshold) & (acct_train['SUSPICIOUS']==0)).sum()
summary_train['tn_count'] = ((acct_train[target_feature]<threshold) & (acct_train['SUSPICIOUS']==0)).sum()
summary_train['fn_count'] = ((acct_train[target_feature]<threshold) & (acct_train['SUSPICIOUS']==1)).sum()
#summary_train_df = summary_train_df.append(pd.DataFrame(summary_train, index=[0]), ignore_index=True)
pd.DataFrame(summary_train, index=[0])

from sklearn.metrics import confusion_matrix
import seaborn as sns

y_suspicious = acct_train['SUSPICIOUS']
y_alert = (acct_train[target_feature]>=threshold).astype(int)

plt.figure(figsize = (10,8))
sns.heatmap(confusion_matrix(y_suspicious, y_alert), annot=True, cmap='Blues', fmt='g')
plt.xlabel('With Alert')
plt.ylabel('Suspicious')
plt.title('Confusuion Matrix at 75th Percentile')
plt.show()

"""<h3>Threshold Simulation for all Percentile</h3>"""

# target_feature = 'CREDIT_AMT'

# summary_train_df = pd.DataFrame()

# for i in range(1, 100):

#     q = i/100
#     threshold = acct_train[target_feature].quantile(q=q)

#     summary_train = {}
#     summary_train['feature'] = target_feature
#     summary_train['percentile'] = q
#     summary_train['threshold'] = threshold
#     summary_train['no_of_alerts'] = (acct_train[target_feature]>=threshold).sum()
#     summary_train['tp_count'] = ((acct_train[target_feature]>=threshold) & (acct_train['SUSPICIOUS']==1)).sum()
#     summary_train['fp_count'] = ((acct_train[target_feature]>=threshold) & (acct_train['SUSPICIOUS']==0)).sum()
#     summary_train['tn_count'] = ((acct_train[target_feature]<threshold) & (acct_train['SUSPICIOUS']==0)).sum()
#     summary_train['fn_count'] = ((acct_train[target_feature]<threshold) & (acct_train['SUSPICIOUS']==1)).sum()
# #summary_train_df = summary_train_df.append(pd.DataFrame(summary_train, index=[0]), ignore_index=True)
# summary_train_df = pd.concat([summary_train_df, pd.DataFrame([summary_train])], ignore_index=True)

target_feature = 'CREDIT_AMT'

# Use a list to collect rows
summary_train_list = []

for i in range(1, 100):
    q = i / 100
    threshold = acct_train[target_feature].quantile(q=q)

    summary_train = {
        'feature': target_feature,
        'percentile': q,
        'threshold': threshold,
        'no_of_alerts': (acct_train[target_feature] >= threshold).sum(),
        'tp_count': ((acct_train[target_feature] >= threshold) & (acct_train['SUSPICIOUS'] == 1)).sum(),
        'fp_count': ((acct_train[target_feature] >= threshold) & (acct_train['SUSPICIOUS'] == 0)).sum(),
        'tn_count': ((acct_train[target_feature] < threshold) & (acct_train['SUSPICIOUS'] == 0)).sum(),
        'fn_count': ((acct_train[target_feature] < threshold) & (acct_train['SUSPICIOUS'] == 1)).sum()
    }

    summary_train_list.append(summary_train)

# Convert once at the end
summary_train_df = pd.DataFrame(summary_train_list)

summary_train_df

"""<h3>Finding Threshold With Best J Statistic</h3>"""

summary_train_df['tp_rate'] = summary_train_df['tp_count'] / (summary_train_df['tp_count'] + summary_train_df['fn_count'])
summary_train_df['fp_rate'] = summary_train_df['fp_count'] / (summary_train_df['fp_count'] + summary_train_df['tn_count'])
summary_train_df['j_stat'] = summary_train_df['tp_rate'] - summary_train_df['fp_rate']
best_j_stat_df = summary_train_df[summary_train_df['j_stat'] == summary_train_df['j_stat'].max()]
best_j_stat_df

best_percentile_by_j_stat = best_j_stat_df.iloc[0]['percentile']
best_threshold_by_j_stat = best_j_stat_df.iloc[0]['threshold']
best_j_stat = best_j_stat_df.iloc[0]['j_stat']
best_fpr_by_j_stat = best_j_stat_df.iloc[0]['fp_rate']
best_tpr_by_j_stat = best_j_stat_df.iloc[0]['tp_rate']

y_suspicious = acct_train['SUSPICIOUS']
y_alert = (acct_train[target_feature]>=best_threshold_by_j_stat).astype(int)

plt.figure(figsize = (10,8))
sns.heatmap(confusion_matrix(y_suspicious, y_alert), annot=True, cmap='Blues', fmt='g')
plt.xlabel('With Alert')
plt.ylabel('Suspicious')
plt.title(f'Confusuion Matrix at {best_percentile_by_j_stat*100:.0f}th Percentile')
plt.show()

fig, ax = plt.subplots(1, 3 ,figsize=(15,5))
fig.suptitle('J Statistic Optimiziation', fontsize=20)

ax[0].set_title('Percentile vs J Statistic')
ax[0].set_xlabel('Percentile')
ax[0].set_ylabel('J Statistic')
ax[0].plot(summary_train_df['percentile'], summary_train_df['j_stat'])
ax[0].plot(best_percentile_by_j_stat, best_j_stat, marker='*', ls='none', ms=15)
ax[0].annotate(f'q={best_percentile_by_j_stat:.4f}\nj={best_j_stat:.4f}', (best_percentile_by_j_stat, best_j_stat), xytext=(-20,-50), textcoords='offset points')

ax[1].set_title('Threshold vs J Statistic')
ax[1].set_xlabel('Threshold')
ax[1].set_ylabel('J Statistic')
ax[1].plot(summary_train_df['threshold'], summary_train_df['j_stat'])
ax[1].plot(best_threshold_by_j_stat, best_j_stat, marker='*', ls='none', ms=15)
ax[1].annotate(f'threshold={best_threshold_by_j_stat:,.0f}\nj={best_j_stat:.4f}', (best_threshold_by_j_stat, best_j_stat), xytext=(15,-15), textcoords='offset points')

ax[2].set_title('FPR vs TPR')
ax[2].set_xlabel('FPR')
ax[2].set_ylabel('TPR')
ax[2].plot(summary_train_df['fp_rate'], summary_train_df['tp_rate'])
ax[2].plot(best_fpr_by_j_stat, best_tpr_by_j_stat, marker='*', ls='none', ms=15)
ax[2].annotate(f'FPR={best_fpr_by_j_stat:.4f}\nTPR={best_tpr_by_j_stat:.4f}', (best_fpr_by_j_stat, best_tpr_by_j_stat), xytext=(-80,0), textcoords='offset points')

plt.tight_layout()
plt.show()

"""<h3>Finding Threshold With Best F1 Score</h3>"""

summary_train_df['precision'] = summary_train_df['tp_count'] / (summary_train_df['tp_count'] + summary_train_df['fp_count'])
summary_train_df['recall'] = summary_train_df['tp_rate']
summary_train_df['f1'] = (2 * summary_train_df['precision'] * summary_train_df['recall']) / (summary_train_df['precision'] + summary_train_df['recall'])
best_f1_df = summary_train_df[summary_train_df['f1'] == summary_train_df['f1'].max()]
best_f1_df.drop(columns=['tp_rate','fp_rate','j_stat'])

best_percentile_by_f1 = best_f1_df.iloc[0]['percentile']
best_threshold_by_f1 = best_f1_df.iloc[0]['threshold']
best_f1 = best_f1_df.iloc[0]['f1']
best_precision_by_f1 = best_f1_df.iloc[0]['precision']
best_recall_by_f1 = best_f1_df.iloc[0]['recall']

y_suspicious = acct_train['SUSPICIOUS']
y_alert = (acct_train[target_feature]>=best_threshold_by_f1).astype(int)

plt.figure(figsize = (10,8))
sns.heatmap(confusion_matrix(y_suspicious, y_alert), annot=True, cmap='Blues', fmt='g')
plt.xlabel('With Alert')
plt.ylabel('Suspicious')
plt.title(f'Confusuion Matrix at {best_percentile_by_f1*100:.0f}th Percentile')
plt.show()

fig, ax = plt.subplots(1, 3 ,figsize=(15,5))
fig.suptitle('F1 Score Optimiziation', fontsize=20)

ax[0].set_title('Percentile vs F1 Score')
ax[0].set_xlabel('Percentile')
ax[0].set_ylabel('F1 Score')
ax[0].plot(summary_train_df['percentile'], summary_train_df['f1'])
ax[0].plot(best_percentile_by_f1, best_f1, marker='*', ls='none', ms=15)
ax[0].annotate(f'q={best_percentile_by_f1:.4f}\nf1={best_f1:.4f}', (best_percentile_by_f1,best_f1), xytext=(-20,-35), textcoords='offset points')

ax[1].set_title('Threshold vs F1 Score')
ax[1].set_xlabel('Threshold')
ax[1].set_ylabel('F1 Score')
ax[1].plot(summary_train_df['threshold'], summary_train_df['f1'])
ax[1].plot(best_threshold_by_f1, best_f1, marker='*', ls='none', ms=15)
ax[1].annotate(f'threshold={best_threshold_by_f1:,.0f}\nf1={best_f1:.4f}', (best_threshold_by_f1,best_f1), xytext=(20,-15), textcoords='offset points')

ax[2].set_title('Precision vs Recall')
ax[2].set_xlabel('Recall')
ax[2].set_ylabel('Precision')
ax[2].plot(summary_train_df['recall'], summary_train_df['precision'])
ax[2].plot(best_recall_by_f1, best_precision_by_f1, marker='*', ls='none', ms=15)
ax[2].annotate(f'recall={best_recall_by_f1:.4f}\nprecision={best_precision_by_f1:.4f}', (best_recall_by_f1, best_precision_by_f1), xytext=(-50,15), textcoords='offset points')

plt.tight_layout()
plt.show()

"""<h2>Compare J Statistic and F1 Score Recommendation</h2>"""

columns = ['percentile','threshold','no_of_alerts','tp_count','fp_count','tn_count','fn_count']
j_stat_vs_f1 = pd.concat([best_j_stat_df[columns].T,best_f1_df[columns].T], axis=1)
j_stat_vs_f1.columns = ['J Statistic','F1 Score']
j_stat_vs_f1.index.names=[target_feature]
j_stat_vs_f1

"""- Recommendation from F1 Score is adopted to minimize number of false negative. Cut-off threshold = $12,412,188.7940

<h2>Validate Threshold Setting With Test Set</h2>
"""

best_evaluation = best_f1_df
threshold = best_threshold_by_f1

summary_test = {}

summary_test['feature'] = target_feature
summary_test['threshold'] = threshold
summary_test['no_of_alerts'] = (acct_test[target_feature]>=threshold).sum()
summary_test['tp_count'] = ((acct_test[target_feature]>=threshold) & (acct_test['SUSPICIOUS']==1)).sum()
summary_test['fp_count'] = ((acct_test[target_feature]>=threshold) & (acct_test['SUSPICIOUS']==0)).sum()
summary_test['tn_count'] = ((acct_test[target_feature]<threshold) & (acct_test['SUSPICIOUS']==0)).sum()
summary_test['fn_count'] = ((acct_test[target_feature]<threshold) & (acct_test['SUSPICIOUS']==1)).sum()

summary_test_df = pd.DataFrame(summary_test, index=[0])

summary_test_df['tp_rate'] = summary_test_df['tp_count'] / (summary_test_df['tp_count'] + summary_test_df['fn_count'])
summary_test_df['fp_rate'] = summary_test_df['fp_count'] / (summary_test_df['fp_count'] + summary_test_df['tn_count'])
summary_test_df['j_stat'] = summary_test_df['tp_rate'] - summary_test_df['fp_rate']

summary_test_df['precision'] = summary_test_df['tp_count'] / (summary_test_df['tp_count'] + summary_test_df['fp_count'])
summary_test_df['recall'] = summary_test_df['tp_rate']
summary_test_df['f1'] = (2 * summary_test_df['precision'] * summary_test_df['recall']) / (summary_test_df['precision'] + summary_test_df['recall'])

comparison = pd.concat([
    best_evaluation.drop(columns=['feature','percentile']).head(1).T,
    summary_test_df.drop(columns=['feature']).T], axis=1)
comparison.columns=['train','test']
comparison.index.names = [target_feature]
comparison['pct_change'] = (comparison['test'] - comparison['train']) / comparison['train']

comparison

"""<h2>Bonus: Evaluate Scenario Effectiveness</h2>"""

import numpy as np
auc = -np.trapz(summary_train_df['tp_rate'], summary_train_df['fp_rate'])

plt.figure(figsize=(7,6))
plt.plot(summary_train_df['fp_rate'], summary_train_df['tp_rate'], label=f'ROC curve (area = {auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.title(f'ROC & AUC for {target_feature}')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.figure(figsize=(7,6))
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.title('ROC & AUC')
plt.tight_layout()

for target_feature in acct_train.columns[1:]:
    summary_roc_list = []

    for i in range(1, 100):
        threshold = acct_train[target_feature].quantile(q=i/100)

        tp = ((acct_train[target_feature] >= threshold) & (acct_train['SUSPICIOUS'] == 1)).sum()
        fp = ((acct_train[target_feature] >= threshold) & (acct_train['SUSPICIOUS'] == 0)).sum()
        tn = ((acct_train[target_feature] < threshold) & (acct_train['SUSPICIOUS'] == 0)).sum()
        fn = ((acct_train[target_feature] < threshold) & (acct_train['SUSPICIOUS'] == 1)).sum()

        tp_rate = tp / (tp + fn) if (tp + fn) > 0 else 0
        fp_rate = fp / (fp + tn) if (fp + tn) > 0 else 0

        summary_roc_list.append({'tp_rate': tp_rate, 'fp_rate': fp_rate})

    summary_roc_df = pd.DataFrame(summary_roc_list)
    auc = -np.trapz(summary_roc_df['tp_rate'], summary_roc_df['fp_rate'])

    plt.plot(summary_roc_df['fp_rate'], summary_roc_df['tp_rate'], label=f'{target_feature}: {auc:.4f}')

plt.legend(loc='lower right')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, roc_curve, classification_report
import joblib

# Define features and target
features = ['CREDIT_AMT', 'CREDIT_COUNT', 'CREDIT_CTPY', 'DEBIT_AMT', 'DEBIT_COUNT', 'DEBIT_CTPY']
X = acct_train[features]
y = acct_train['SUSPICIOUS']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train_scaled, y_train)

# Save the model and scaler
joblib.dump(rf_model, 'rf_aml_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

# Predictions
y_pred = rf_model.predict(X_test_scaled)
y_pred_proba = rf_model.predict_proba(X_test_scaled)[:, 1]

# Metrics
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Plot ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
plt.figure(figsize=(7,6))
plt.plot(fpr, tpr, label=f'Random Forest (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (FPR)')
plt.ylabel('True Positive Rate (TPR)')
plt.title('ROC Curve - Random Forest Model')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('rf_roc_curve.png')
plt.show()

# Feature Importance
feature_importance = pd.DataFrame({
    'Feature': features,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(8,6))
plt.barh(feature_importance['Feature'], feature_importance['Importance'])
plt.xlabel('Importance')
plt.title('Feature Importance - Random Forest Model')
plt.tight_layout()
plt.savefig('feature_importance.png')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import seaborn as sns
import matplotlib.pyplot as plt

# Features and target
feature_cols = ['CREDIT_AMT', 'DEBIT_AMT', 'CREDIT_COUNT', 'DEBIT_COUNT']  # adjust if needed
X = acct_train[feature_cols]
y = acct_train['SUSPICIOUS']

# Split the data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

# Neural Network model
mlp_model = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam',
                          max_iter=1000, random_state=42)
mlp_model.fit(X_train, y_train)

# Predictions
y_pred = mlp_model.predict(X_val)
y_prob = mlp_model.predict_proba(X_val)[:,1]

# Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

print("\nClassification Report:")
print(classification_report(y_val, y_pred))

print(f"AUC Score: {roc_auc_score(y_val, y_prob):.3f}")

# Plot Confusion Matrix
sns.heatmap(confusion_matrix(y_val, y_pred), annot=True, fmt='d', cmap='Purples')
plt.title('Neural Network Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

#comparing between two models
# Define features and target
features_rf = ['CREDIT_AMT', 'CREDIT_COUNT', 'CREDIT_CTPY', 'DEBIT_AMT', 'DEBIT_COUNT', 'DEBIT_CTPY']
features_nn = ['CREDIT_AMT', 'DEBIT_AMT', 'CREDIT_COUNT', 'DEBIT_COUNT']
target = 'SUSPICIOUS'

# Common train-test split
X = acct_train[list(set(features_rf + features_nn))]
y = acct_train[target]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ============================
# Train Random Forest Model
# ============================
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train_scaled, y_train)
rf_pred = rf_model.predict(X_test_scaled)
rf_proba = rf_model.predict_proba(X_test_scaled)[:, 1]

# ============================
# Train Neural Network Model
# ============================
mlp_model = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam',
                          max_iter=1000, random_state=42)
mlp_model.fit(X_train_scaled, y_train)
mlp_pred = mlp_model.predict(X_test_scaled)
mlp_proba = mlp_model.predict_proba(X_test_scaled)[:, 1]

# ============================
# Comparison Table
# ============================
results_df = pd.DataFrame(results)
print("\nModel Comparison:")
print(results_df)
print("----------------------------------------------------")

# ============================
# Plot ROC Curves
# ============================
rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_proba)
mlp_fpr, mlp_tpr, _ = roc_curve(y_test, mlp_proba)

plt.figure(figsize=(8,6))
plt.plot(rf_fpr, rf_tpr, label=f'Random Forest (AUC = {results_df.iloc[0]["ROC AUC"]:.4f})')
plt.plot(mlp_fpr, mlp_tpr, label=f'Neural Network (AUC = {results_df.iloc[1]["ROC AUC"]:.4f})')
plt.plot([0,1], [0,1], linestyle='--', color='grey')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend(loc='lower right')
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================
# Plot Confusion Matrices
# ============================
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.heatmap(confusion_matrix(y_test, rf_pred), annot=True, fmt='d', cmap='Blues', ax=axes[0])
axes[0].set_title("Random Forest Confusion Matrix")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

sns.heatmap(confusion_matrix(y_test, mlp_pred), annot=True, fmt='d', cmap='Purples', ax=axes[1])
axes[1].set_title("Neural Network Confusion Matrix")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()